In [1]:
import cv2
import scipy
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
from PIL import Image
from sklearn.model_selection import train_test_split


In [32]:
print(type(y_train))

<class 'torch.Tensor'>


In [8]:
print(y_trainHot)

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [11]:
print(y_trainHot[963])

[0. 0. 1. 0. 0.]


# Model architecture 

In [3]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()
        self.conv1 = nn.Conv2d(3,6,5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84,4)
        
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

cnn = CNN()

In [4]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(cnn.parameters(), lr=0.001, momentum=0.9)

In [5]:
def train_model(model, X_train, y_train):
    running_loss = 0.0
    for i, data in enumerate(trainloader):
        X_train,y_train = data 
        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        output = model(X_train)
                
        loss = criterion(output, y_train)
        loss.backward()
        optimizer.step()

        # print statistics
                running_loss += loss.item()
                if i % 2000 == 1999:    # print every 2000 mini-batches
                    print('[%d, %5d] loss: %.3f' %
                          (epoch + 1, i + 1, running_loss / 2000))
                    running_loss = 0.0

    print('Finished Training')

In [6]:
train_model(cnn, 3, X_train, y_train)

RuntimeError: Given groups=1, weight of size [10, 3, 5, 5], expected input[11831, 80, 60, 3] to have 3 channels, but got 80 channels instead

In [47]:
def resize(image):
    #print('dimension before resize {} '.format(image.shape))
    WIDTH= 500#constant
    HEIGHT= 500#constant
    dim = (WIDTH, HEIGHT)
    resized=cv2.resize(image,dim,interpolation=cv2.INTER_AREA)
    #print('dimension after resize {}'.format(resized.shape))
    return resized

In [2]:

def get_data(folder):
    X = []
    y = []
    for wbc_type in os.listdir(folder):
        if not wbc_type.startswith('.'):
            if wbc_type in ['NEUTROPHIL']:
                label = 1
    
            elif wbc_type in ['EOSINOPHIL']:
                label = 2

            elif wbc_type in ['MONOCYTE']:
                label = 3  

            elif wbc_type in ['LYMPHOCYTE']:
                label = 4 

            else:
                label = 5

            for image_filename in tqdm(os.listdir(folder + wbc_type)):
                imagepath=folder + wbc_type + '/' + image_filename
               # print('imagepath:{}'.format(folder + wbc_type + '/' + image_filename))
                img_file = cv2.imread(folder + wbc_type + '/' + image_filename)
                if img_file is not None:
                    #img_file_resized=resize(img_file)
                    #img_file = img_file.reshape((-1, 500, 500, 3))
                    img_arr = np.asarray(img_file)
                    
                    #np.array(Image.fromarray(img_arr).resize(size=(60, 80)))
                    #print('img_arr:',img_arr)
                    #print(img_arr.shape)
                    #X=X+img_arr
                    #y= y+label
                    X.append(img_arr)
                    y.append(label)
                #print('array',y)

        X_new = np.asarray(X)
        #print(X)
        y_new = np.asarray(y)
 
    return X_new,y_new

X_train, y_train = get_data('C:\\Users\\jodv\\YPcase\\kickstart2020\\Data\\cutImage\\TRAIN\\')
#X_test, y_test = get_data('Desktop/dataset2-master/images/TEST/')

# Encode labels to hot vectors (ex# : 2 -> [0,0,1,0,0,0,0,0,0,0])
from keras.utils.np_utils import to_categorical
y_trainHot = to_categorical(y_train, num_classes = 5)
#y_testHot = to_categorical(y_test, num_classes = 5)
#z_trainHot = to_categorical(z_train, num_classes = 2)
#z_testHot = to_categorical(z_test, num_classes = 2)

100%|█████████████████████████████████████████████████████████████████████████████████| 69/69 [00:00<00:00, 115.86it/s]
Using TensorFlow backend.
c:\users\jodv\anaconda3\envs\kickstart1020\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\jodv\anaconda3\envs\kickstart1020\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\jodv\anaconda3\envs\kickstart1020\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will b

In [85]:
y_train

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [23]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, Dropout
from keras.layers.pooling import *
#create model
model = Sequential()
#add model layers
model.add(Conv2D(4, kernel_size=4, activation='relu', input_shape=(500,500,3)))
model.add(MaxPooling2D(pool_size=(2, 2), strides=4, padding='valid'))

#model.add(Conv2D(2, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(5, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_16 (Conv2D)           (None, 497, 497, 4)       196       
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 124, 124, 4)       0         
_________________________________________________________________
flatten_7 (Flatten)          (None, 61504)             0         
_________________________________________________________________
dense_10 (Dense)             (None, 5)                 307525    
Total params: 307,721
Trainable params: 307,721
Non-trainable params: 0
_________________________________________________________________


In [24]:
from sklearn.model_selection import train_test_split

# Split the data
x_train, x_valid, y_train, y_valid = train_test_split(X_train, y_trainHot, test_size=0.1, shuffle= True)

In [25]:
batch_size = 64
epochs = 15

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

model.fit(x_train, y_train, validation_data=(x_valid,y_valid) ,batch_size=batch_size, epochs=epochs)

Train on 341 samples, validate on 38 samples
Epoch 1/15
341/341 [==============================] - 63s 184ms/step - loss: 9.5480 - acc: 0.4076 - val_loss: 9.7557 - val_acc: 0.3947
Epoch 2/15
341/341 [==============================] - 60s 175ms/step - loss: 9.5007 - acc: 0.4106 - val_loss: 9.7557 - val_acc: 0.3947
Epoch 3/15
341/341 [==============================] - 59s 173ms/step - loss: 9.5007 - acc: 0.4106 - val_loss: 9.7557 - val_acc: 0.3947
Epoch 4/15
341/341 [==============================] - 60s 175ms/step - loss: 9.5007 - acc: 0.4106 - val_loss: 9.7557 - val_acc: 0.3947
Epoch 5/15
341/341 [==============================] - 60s 175ms/step - loss: 9.5007 - acc: 0.4106 - val_loss: 9.7557 - val_acc: 0.3947
Epoch 6/15
341/341 [==============================] - 60s 175ms/step - loss: 9.5007 - acc: 0.4106 - val_loss: 9.7557 - val_acc: 0.3947
Epoch 7/15
341/341 [==============================] - 52s 153ms/step - loss: 9.5007 - acc: 0.4106 - val_loss: 9.7557 - val_acc: 0.3947
Epoch 8/15

In [27]:
model.save('C:\\Users\\jodv\\YPcase\\kickstart2020\\App\\Models\\classificationModel\\model1.h5')

In [14]:
# importing OpenCV(cv2) module 
import cv2 
%matplotlib inline
  
# Save image in set directory 
# Read RGB image 
img=[]
img.append(cv2.imread('C:\\Users\\jodv\\YPcase\\kickstart2020\\Data\\cutImage\\TRAIN\\LYMPHOCYTE\\_19_9399.jpeg_0.jpg')) 
img.append(cv2.imread('C:\\Users\\jodv\\YPcase\\kickstart2020\\Data\\cutImage\\TRAIN\\LYMPHOCYTE\\_19_9767.jpeg_0.jpg')) 
img.append(cv2.imread('C:\\Users\\jodv\\YPcase\\kickstart2020\\Data\\cutImage\\TRAIN\\LYMPHOCYTE\\_19_9940.jpeg_0.jpg')) 
img.append(cv2.imread('C:\\Users\\jodv\\YPcase\\kickstart2020\\Data\\cutImage\\TRAIN\\LYMPHOCYTE\\_19_9945.jpeg_0.jpg')) 




#cv2.imshow('image', img)  
# from matplotlib import pyplot as plt
# plt.imshow(img)
# plt.show()

In [ ]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])